[tool.poetry]
name = "cve"
version = "0.1.0"
description = ""
authors = ["xh4vm <h4vm@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
black = "^24.4.2"
isort = "^5.13.2"
asyncio = "^3.4.3"
asyncclick = "^8.1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
