x-base-service: &base_service
  env_file: .env
  networks:
    - confluence

x-confluence-service: &base_confluence
  image: atlassian/confluence:${VERSION}
  environment:
    - TZ=Etc/UTC
  depends_on:
    db:
      condition: service_healthy
  restart: always

services:
  confluence01:
    <<: *base_service
    <<: *base_confluence
    container_name: confluence01
    ports:
      - "8090:8090"
    volumes:
      - confluence-data:/var/confluence

  db:
    <<: *base_service
    image: postgres:16.3-alpine
    hostname: db
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -D ${DB_NAME} > /dev/null; if [[ $$? == 0 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  confluence:
    driver: bridge

volumes:
  confluence-data:
  postgres-data:
